### PR TITLE
Hide growth session topics for sessions that have past

### PR DESCRIPTION
**Pull request by IthJ**
Addressing Issue: https://github.com/vehikl/vehikl-growth-sessions/issues/204

With Topics
image

Without Topics
image

Would love feedback/suggestions

### CODE REVIEW

**Comment by Milozap** [comment]
This Pr checks if growth session is from yesterday and then hides their topics right? 
Do you think it would be better to add a filter for full growth sessions (for example 4 out of 4) in this PR or the next one?

**Comment by IthJ** [comment]
> This Pr checks if growth session is from yesterday and then hides their topics right? Do you think it would be better to add a filter for full growth sessions (for example 4 out of 4) in this PR or the next one?

This sounds like it could be a whole new feature. Could you make an issue for this with a further explanation?

**Comment by Milozap** [comment]
> > This Pr checks if growth session is from yesterday and then hides their topics right? Do you think it would be better to add a filter for full growth sessions (for example 4 out of 4) in this PR or the next one?
> 
> This sounds like it could be a whole new feature. Could you make an issue for this with a further explanation?

Yea I think I wasn't clear in this issue but that's what I meant by `It would be great to have a way to filter out growth sessions that are full.`
I meant a checkbox or some other UI element that would allow users to hide full growth sessions if they are looking only for ones they can join.

Does this description work better? I don't want to block your work because it looks good thought so I will approve once the branch is updated to new base.

image

**Comment by FRFlor** [comment]
The branch was out of date because I merged a couple of other PRs since then. 
I've updated his branch to the latest master now. 

I would love to talk more about this PR over here, I personally would prefer to be able to see the description of past growth sessions. 

In regards to adding a checkbox to filter out Growth sessions that don't have spots available, that sounds like a great idea.

**Comment by ANDREYDEN** [comment]
@FRFlor Does this call for a settings page? If different users prefer different views of the GS list, should we allow them to configure their preferences?

**Comment by FRFlor** [comment]
> @FRFlor Does this call for a settings page? If different users prefer different views of the GS list, should we allow them to configure their preferences?

I think so. Personal preferences fit well in this case. 

We could include things like:
- Display name
- Theme: Dark/Light
- Preferred visibility: All / Public Only / Private Only 
- **Display description of past sessions: On / Off**

**Comment by ANDREYDEN** [comment]
@FRFlor, since this requires more work, should we close this PR and implement the preferences page/dialog first?

**Comment by FRFlor** [comment]
> @FRFlor, since this requires more work, should we close this PR and implement the preferences page/dialog first?

Yeah, I agree. 

Are you okay with that @IthJ ? 

We could work on getting a preferences page live as soon as possible.

**Comment by IthJ** [comment]
> > @FRFlor, since this requires more work, should we close this PR and implement the preferences page/dialog first?
> 
> Yeah, I agree.
> 
> Are you okay with that @IthJ ?
> 
> We could work on getting a preferences page live as soon as possible.

Sure, let's close this and add it to the preferences page.

**Pull request closed without merging**
